version: '3'
services:
  web:
    build: .
    command: python bot.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      LINKDING_TOKEN: "${LINKDING_TOKEN}"
      LINKDING_URL: "${LINKDING_URL}"